### ISSUE TITLE
Cannot find module 'babel-runtime/core-js/object/entries'

### ISSUE THREAD

**Issue by alobodig** [du5rte/graphql-mongodb-projection#8]
Since d855eea5a9775295810d2c9044802de48e60c63f I am getting the following error on a fresh install.

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/entries'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/albert/Projects/pledgeit-services/users/node_modules/graphql-mongodb-projection/lib/index.js:7:16)
    at Module._compile (module.js:643:30)
    at Module._compile (/Users/albert/Projects/pledgeit-services/users/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (/Users/albert/Projects/pledgeit-services/users/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/albert/Projects/pledgeit-services/users/lib/graphql/userResolvers.js:1:1)
    at Module._compile (module.js:643:30)
    at Module._compile (/Users/albert/Projects/pledgeit-services/users/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (/Users/albert/Projects/pledgeit-services/users/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

Adding `babel-runtime` to the packages seems to fix this.

**Comment by du5rte** [comment]
@alobodig Seems like it cames from me adding code with `Object.entries` maybe I already had `babel-runtime` installed on my machine. but I'm curious how the tests missed it... do want to submit a commit with that fix?
